### ISSUE TITLE
Cant clone array of strings in js

### ISSUE THREAD

**Issue by ianharrigan** [thomasuster/cloner#2]
When trying to do this:

```haxe
var cloner = new Cloner();
trace(cloner.clone(["1", "2", "3"]));
```
I get the following:
```
ObjectMap.hx:46 Uncaught TypeError: Cannot create property '__id__' on string '1'
    at haxe_ds_ObjectMap.set (ObjectMap.hx:46)
    at cloner_Cloner._clone (Cloner.hx:55)
    at cloner_Cloner.cloneArray (Cloner.hx:84)
    at f (Uint8Array.hx:93)
    at cloner_Cloner.handleClass (Cloner.hx:78)
    at cloner_Cloner._clone (Cloner.hx:55)
    at cloner_Cloner.clone (Cloner.hx:30)
```

Any thoughts?

Cheers,
Ian

**Comment by JeremyGiner** [comment]
I made a quick fix for it about a year ago: [https://github.com/JeremyGiner/cloner](https://github.com/JeremyGiner/cloner).
Your example seems to work fine with it.

Although I wouldn't recommend using this code unless you really need to.

**Comment by thomasuster** [comment]
@ianharrigan I haven't found a JS test runner that can be run through Travis, so I just added the change manually and tested it. That work okay for you? https://github.com/thomasuster/cloner/commit/cba37b76ae21bbcb34d153b45bfa30033bae3346

**Comment by ianharrigan** [comment]
Hi sorry, completely forgot about this. My Bad. Thanks for closing. I had a quick check and yes, all worked. 

Cheers,
Ian
