### ISSUE TITLE
Cloning anonymous structure with property set to null throws error

### ISSUE THREAD

**Issue by Joncom** [thomasuster/cloner#5]
Cloning the following example object throws an error:

```
{
    uuid: null,
    seed: null,
    actions: [],
    debug: []
}
```

"TypeError: Cannot read property '__name__' of null"

The following patch seems to fix things:

```
$ git diff
diff --git a/game/Kha/Sources/cloner/Cloner.hx b/game/Kha/Sources/cloner/Cloner.hx
index 0bf4cf97..1d7b7394 100644
--- a/game/Kha/Sources/cloner/Cloner.hx
+++ b/game/Kha/Sources/cloner/Cloner.hx
@@ -33,6 +33,9 @@ class Cloner {
     }

     public function _clone <T> (v:T):T {
+        if(v == null) {
+            return null;
+        }
         #if js
         if(Std.is(v, String))
             return v;
```

**Comment by thomasuster** [comment]
@Joncom Hey there, would you submit a pull request with a unit test?

**Comment by Joncom** [comment]
Sorry I don’t have the time right now. However, hopefully it’s obvious that
this change is super small and simple and not going to break anything.

**Comment by NQNStudios** [comment]
I forked the repo and turned @Joncom's example into a unit test:
```
public function testAnonObjectNullField():Void {
        // Test for https://github.com/thomasuster/cloner/issues/5
        var clone = cloner.clone({
            uuid: null,
            seed: null,
            actions: [],
            debug: []
        });

        assertEquals(null, clone.uuid);
        assertEquals(null, clone.seed);
    }
```

Running the tests with Haxe 4 and hx3compat, this test passes when `./test.sh` is run. Joncom, what target language, platform, and Haxe version were you using when you found the error?

**Comment by Joncom** [comment]
Hello. It was a couple years ago. I don’t recall which version I was using
at the time. Sorry about that.
